import 'domain_models.dart';

const sampleHomeSnapshot = HomeSnapshot(
  premiumState: PremiumState.free,
  adTier: AdTier.freeWithAds,
  adConsentRequired: true,
  adConsentGranted: false,
  analyticsConsent: false,
  accountModeLabel: 'Anonymous by default, email login optional later',
  languageCode: 'en',
  timezone: 'Europe/Amsterdam',
  viewingCountryCode: 'NL',
  fighters: [
    FighterSummary(
      id: 'ftr_katie_taylor',
      name: 'Katie Taylor',
      sport: Sport.boxing,
      organizationHint: 'Matchroom',
      recordLabel: '24-1-0',
      nationalityLabel: 'Ireland',
      headline: 'Undisputed championship-level boxing star',
      nextAppearanceLabel: 'Sat 18 Apr',
      isFollowed: true,
      nickname: 'The Bray Bomber',
    ),
    FighterSummary(
      id: 'ftr_amanda_serrano',
      name: 'Amanda Serrano',
      sport: Sport.boxing,
      organizationHint: 'Matchroom',
      recordLabel: '47-3-1',
      nationalityLabel: 'Puerto Rico',
      headline: 'Multi-division champion with elite volume and pressure',
      nextAppearanceLabel: 'Sat 18 Apr',
      isFollowed: false,
    ),
    FighterSummary(
      id: 'ftr_alex_pereira',
      name: 'Alex Pereira',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '11-3-0',
      nationalityLabel: 'Brazil',
      headline: 'Explosive striker with title-fight gravity',
      nextAppearanceLabel: 'Sun 10 May',
      isFollowed: true,
      nickname: 'Poatan',
    ),
    FighterSummary(
      id: 'ftr_magomed_ankalaev',
      name: 'Magomed Ankalaev',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '21-1-1',
      nationalityLabel: 'Russia',
      headline: 'Calculated pressure fighter with championship upside',
      nextAppearanceLabel: 'Sun 10 May',
      isFollowed: false,
    ),
    FighterSummary(
      id: 'ftr_renato_moicano',
      name: 'Renato Moicano',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '21-6-1',
      nationalityLabel: 'Brazil',
      headline: 'Veteran lightweight with slick grappling transitions',
      nextAppearanceLabel: 'Sun 5 Apr',
      isFollowed: false,
    ),
    FighterSummary(
      id: 'ftr_chris_duncan',
      name: 'Chris Duncan',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '13-2-0',
      nationalityLabel: 'Scotland',
      headline: 'Aggressive finisher pushing into bigger UFC spots',
      nextAppearanceLabel: 'Sun 5 Apr',
      isFollowed: false,
    ),
    FighterSummary(
      id: 'ftr_virna_jandiroba',
      name: 'Virna Jandiroba',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '23-4-0',
      nationalityLabel: 'Brazil',
      headline: 'Elite submission grappler climbing the strawweight ranks',
      nextAppearanceLabel: 'Sun 5 Apr',
      isFollowed: false,
    ),
    FighterSummary(
      id: 'ftr_tabatha_ricci',
      name: 'Tabatha Ricci',
      sport: Sport.mma,
      organizationHint: 'UFC',
      recordLabel: '12-3-0',
      nationalityLabel: 'Brazil',
      headline: 'Strong transitional wrestler with steady momentum',
      nextAppearanceLabel: 'Sun 5 Apr',
      isFollowed: false,
      nickname: 'Baby Shark',
    ),
  ],
  events: [
    EventSummary(
      id: 'evt_matchroom_taylor_serrano',
      organization: 'Matchroom',
      sport: Sport.boxing,
      title: 'Taylor vs Serrano III',
      tagline: 'A championship rematch built for a major Dublin night.',
      locationLabel: 'Dublin, Ireland',
      venueLabel: '3Arena',
      localDateLabel: 'Sat 18 Apr',
      localTimeLabel: '21:00',
      eventLocalTimeLabel: '20:00 local',
      selectedCountryCode: 'NL',
      isFollowed: true,
      sourceLabel: 'Official promoter schedule',
      watchProviders: [
        WatchProviderSummary(
          label: 'DAZN',
          countryCode: 'NL',
          kind: ProviderKind.streaming,
          confidenceLabel: 'Confirmed',
        ),
      ],
      bouts: [
        BoutSummary(
          id: 'bout_taylor_serrano',
          slotLabel: 'Main event',
          fighterAId: 'ftr_katie_taylor',
          fighterAName: 'Katie Taylor',
          fighterBId: 'ftr_amanda_serrano',
          fighterBName: 'Amanda Serrano',
          weightClass: 'Lightweight',
          isMainEvent: true,
          includesFollowedFighter: true,
        ),
      ],
    ),
    EventSummary(
      id: 'evt_ufc_327',
      organization: 'UFC',
      sport: Sport.mma,
      title: 'Pereira vs Ankalaev',
      tagline: 'A sharp title-fight card with real championship stakes.',
      locationLabel: 'Miami, Florida, USA',
      venueLabel: 'Kaseya Center',
      localDateLabel: 'Sun 10 May',
      localTimeLabel: '04:00',
      eventLocalTimeLabel: 'Sat 9 May • 9:00 PM EDT',
      selectedCountryCode: 'NL',
      isFollowed: false,
      sourceLabel: 'Official UFC schedule',
      watchProviders: [
        WatchProviderSummary(
          label: 'Discovery+ / TNT Sports',
          countryCode: 'NL',
          kind: ProviderKind.streaming,
          confidenceLabel: 'Likely',
        ),
      ],
      bouts: [
        BoutSummary(
          id: 'bout_pereira_ankalaev',
          slotLabel: 'Main event',
          fighterAId: 'ftr_alex_pereira',
          fighterAName: 'Alex Pereira',
          fighterBId: 'ftr_magomed_ankalaev',
          fighterBName: 'Magomed Ankalaev',
          weightClass: 'Light Heavyweight',
          isMainEvent: true,
          includesFollowedFighter: true,
        ),
      ],
    ),
    EventSummary(
      id: 'evt_ufc_fight_night_moicano_duncan',
      organization: 'UFC',
      sport: Sport.mma,
      title: 'Moicano vs Duncan',
      tagline: 'A compact UFC Fight Night card with strong lightweight stakes.',
      locationLabel: 'Las Vegas, Nevada, USA',
      venueLabel: 'UFC APEX',
      localDateLabel: 'Sun 5 Apr',
      localTimeLabel: '02:00',
      eventLocalTimeLabel: 'Sat 4 Apr • 8:00 PM EDT',
      selectedCountryCode: 'NL',
      isFollowed: true,
      sourceLabel: 'Official UFC schedule',
      watchProviders: [
        WatchProviderSummary(
          label: 'UFC Fight Pass',
          countryCode: 'NL',
          kind: ProviderKind.streaming,
          confidenceLabel: 'Likely',
        ),
      ],
      bouts: [
        BoutSummary(
          id: 'bout_moicano_duncan',
          slotLabel: 'Main event',
          fighterAId: 'ftr_renato_moicano',
          fighterAName: 'Renato Moicano',
          fighterBId: 'ftr_chris_duncan',
          fighterBName: 'Chris Duncan',
          weightClass: 'Lightweight',
          isMainEvent: true,
          includesFollowedFighter: false,
        ),
        BoutSummary(
          id: 'bout_jandiroba_ricci',
          slotLabel: 'Co-main',
          fighterAId: 'ftr_virna_jandiroba',
          fighterAName: 'Virna Jandiroba',
          fighterBId: 'ftr_tabatha_ricci',
          fighterBName: 'Tabatha Ricci',
          weightClass: 'Strawweight',
          isMainEvent: false,
          includesFollowedFighter: false,
        ),
      ],
    ),
  ],
);
